version: "3.8"

services:
  web:
    build: .
    image: weather_app_web
    container_name: weather_app_web
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_path:/bundle
    depends_on:
      - db
    environment:
      - BUNDLE_PATH=/bundle/vendor
  db:
    image: postgres:13.4
    container_name: weather_app_db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5800:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  bundle_path:
