name: CI/CD

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.4-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup ENV vars
        run: cp .env.ci .env

      - name: Run Rubocop
        run: bundle exec rubocop

      - name: Setup DB
        run: bundle exec rails db:test:prepare

      - name: Run Tests
        run: bundle exec rspec